{
 "title": "Forcasting Weather",
 "time": { "from": "now", "to": "now+15d" },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# 🌦️ Forecasting Weather Yogyakarta\r\n\r\n### AI-Powered Meteorological Prediction\r\n\r\nSistem prediksi cuaca berbasis **Deep Learning (LSTM)** yang dirancang untuk memantau kondisi atmosfer di wilayah Yogyakarta dan sekitarnya.\r\n\r\n---\r\n\r\n### 📊 Model Statistics\r\n- **Architecture**: Multi-layer LSTM (Long Short-Term Memory)\r\n- **Hardware**: NVIDIA GPU Accelerated (CUDA)\r\n- **Horizon**: 60-Day Future Forecast\r\n- **Parameters**: Temp, Humidity, Rain, Pressure (hPa)\r\n\r\n### 🔗 Open Source\r\n\r\n👉 [**GitHub Repository**](https://github.com/ernestoyoofi/forcasting-weather-yogyakarta)"
   }
  },
  {
   "title": "Suhu - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Suhu - Maksimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Maksimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Maksimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Maksimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Suhu - Minimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Minimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Minimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Minimal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Suhu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Suhu\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Tekanan Udara\")"
    }
   ]
  },
  {
   "title": "Curah Hujan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Curah Hujan\")"
    }
   ]
  },
  {
   "title": "Kelembapan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Kelembapan\")"
    }
   ]
  }
 ]
}