{
 "title": "Forcasting Weather",
 "time": { "from": "2026-03-27T17:00:00.000Z", "to": "2026-04-19T16:59:59.000Z" },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# 🌦️ Forecasting Weather Yogyakarta\r\n\r\n### AI-Powered Meteorological Prediction\r\n\r\nSistem prediksi cuaca berbasis **Deep Learning (LSTM)** yang dirancang untuk memantau kondisi atmosfer di wilayah Yogyakarta dan sekitarnya.\r\n\r\n---\r\n\r\n### 📊 Model Statistics\r\n- **Architecture**: Multi-layer LSTM (Long Short-Term Memory)\r\n- **Hardware**: NVIDIA GPU Accelerated (CUDA)\r\n- **Horizon**: 60-Day Future Forecast\r\n- **Parameters**: Temp, Humidity, Rain, Pressure (hPa)\r\n\r\n### 🔗 Open Source\r\n\r\n👉 [**GitHub Repository**](https://github.com/ernestoyoofi/forcasting-weather-yogyakarta)"
   }
  },
  {
   "title": "Suhu - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Rata Rata",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> mean()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Suhu - Maksimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Maksimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Maksimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Maksimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Suhu - Minimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Curah Hujan - Maksimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> max()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Kelembapan - Minimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara - Minimal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> min()\r\n  |> yield(name: \"avg_temperature\")"
    }
   ]
  },
  {
   "title": "Tingkat Curah Hujan",
   "type": "stat",
   "description": "Tingkat hujan rata ratanya",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> mean()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value <= 3.0 then \"Tidak ada\"\r\n              else if r._value <= 5.0 then \"Rendah\"\r\n              else if r._value <= 20.0 then \"Sedang\"\r\n              else if r._value <= 50.0 then \"Tinggi\"\r\n              else \"Badai\"\r\n  }))\r\n  |> group()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tingkat Suhu",
   "type": "stat",
   "description": "Untuk diarea dasar, namun area kota atau luar seperti lapangan bisa bertambah +6 derajat celcius",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> mean()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._value <= 15 then \"Dingin\"\r\n              else if r._value <= 20 then \"Sedang\"\r\n              else if r._value <= 25 then \"Normal\"\r\n              else if r._value <= 30 then \"Panas\"\r\n              else if r._value <= 34 then \"Panas (Diatas Batas)\"\r\n              else \"Melewati Batas Normal\"\r\n  }))\r\n  |> group()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tingkat Suhu +6 - +14 (Jam)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> mean()\r\n  |> map(fn: (r) => ({ r with _value: r._value + 5.0 }))\r\n  |> group()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Suhu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Suhu\")"
    }
   ]
  },
  {
   "title": "Tekanan Udara",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Tekanan Udara\")"
    }
   ]
  },
  {
   "title": "Curah Hujan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"rain\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Curah Hujan\")"
    }
   ]
  },
  {
   "title": "Kelembapan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"weather_forecast\")\r\n  |> range(start: now(), stop: 30d)\r\n  |> filter(fn: (r) => r._measurement == \"forecast\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"Kelembapan\")"
    }
   ]
  }
 ]
}